/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExceptionsRouteImport } from './routes/exceptions'
import { Route as FinishedGoodsRouteImport } from './routes/finished-goods'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ReworkScrapRouteImport } from './routes/rework-scrap'
import { Route as CertificatesIndexRouteImport } from './routes/certificates.index'
import { Route as CertificatesNumberRouteImport } from './routes/certificates.$number'
import { Route as WorkOrdersIndexRouteImport } from './routes/work-orders.index'
import { Route as WorkOrdersIdRouteImport } from './routes/work-orders.$id'
import { Route as WorkOrdersNewRouteImport } from './routes/work-orders.new'
import { Route as WorkOrdersIdIndexRouteImport } from './routes/work-orders.$id.index'
import { Route as WorkOrdersIdBomRouteImport } from './routes/work-orders.$id.bom'
import { Route as WorkOrdersIdConfirmationRouteImport } from './routes/work-orders.$id.confirmation'
import { Route as WorkOrdersIdConsumptionRouteImport } from './routes/work-orders.$id.consumption'
import { Route as WorkOrdersIdEditRouteImport } from './routes/work-orders.$id.edit'
import { Route as WorkOrdersIdQualityRouteImport } from './routes/work-orders.$id.quality'
import { Route as WorkOrdersIdStagesRouteImport } from './routes/work-orders.$id.stages'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExceptionsRoute = ExceptionsRouteImport.update({
  id: '/exceptions',
  path: '/exceptions',
  getParentRoute: () => rootRouteImport,
} as any)
const FinishedGoodsRoute = FinishedGoodsRouteImport.update({
  id: '/finished-goods',
  path: '/finished-goods',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ReworkScrapRoute = ReworkScrapRouteImport.update({
  id: '/rework-scrap',
  path: '/rework-scrap',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesIndexRoute = CertificatesIndexRouteImport.update({
  id: '/certificates/',
  path: '/certificates/',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesNumberRoute = CertificatesNumberRouteImport.update({
  id: '/certificates/$number',
  path: '/certificates/$number',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkOrdersIndexRoute = WorkOrdersIndexRouteImport.update({
  id: '/work-orders/',
  path: '/work-orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkOrdersIdRoute = WorkOrdersIdRouteImport.update({
  id: '/work-orders/$id',
  path: '/work-orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkOrdersNewRoute = WorkOrdersNewRouteImport.update({
  id: '/work-orders/new',
  path: '/work-orders/new',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkOrdersIdIndexRoute = WorkOrdersIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkOrdersIdRoute,
} as any)
const WorkOrdersIdBomRoute = WorkOrdersIdBomRouteImport.update({
  id: '/bom',
  path: '/bom',
  getParentRoute: () => WorkOrdersIdRoute,
} as any)
const WorkOrdersIdConfirmationRoute =
  WorkOrdersIdConfirmationRouteImport.update({
    id: '/confirmation',
    path: '/confirmation',
    getParentRoute: () => WorkOrdersIdRoute,
  } as any)
const WorkOrdersIdConsumptionRoute = WorkOrdersIdConsumptionRouteImport.update({
  id: '/consumption',
  path: '/consumption',
  getParentRoute: () => WorkOrdersIdRoute,
} as any)
const WorkOrdersIdEditRoute = WorkOrdersIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => WorkOrdersIdRoute,
} as any)
const WorkOrdersIdQualityRoute = WorkOrdersIdQualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => WorkOrdersIdRoute,
} as any)
const WorkOrdersIdStagesRoute = WorkOrdersIdStagesRouteImport.update({
  id: '/stages',
  path: '/stages',
  getParentRoute: () => WorkOrdersIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/exceptions': typeof ExceptionsRoute
  '/finished-goods': typeof FinishedGoodsRoute
  '/login': typeof LoginRoute
  '/rework-scrap': typeof ReworkScrapRoute
  '/certificates/$number': typeof CertificatesNumberRoute
  '/work-orders/$id': typeof WorkOrdersIdRouteWithChildren
  '/work-orders/new': typeof WorkOrdersNewRoute
  '/certificates/': typeof CertificatesIndexRoute
  '/work-orders/': typeof WorkOrdersIndexRoute
  '/work-orders/$id/bom': typeof WorkOrdersIdBomRoute
  '/work-orders/$id/confirmation': typeof WorkOrdersIdConfirmationRoute
  '/work-orders/$id/consumption': typeof WorkOrdersIdConsumptionRoute
  '/work-orders/$id/edit': typeof WorkOrdersIdEditRoute
  '/work-orders/$id/quality': typeof WorkOrdersIdQualityRoute
  '/work-orders/$id/stages': typeof WorkOrdersIdStagesRoute
  '/work-orders/$id/': typeof WorkOrdersIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/exceptions': typeof ExceptionsRoute
  '/finished-goods': typeof FinishedGoodsRoute
  '/login': typeof LoginRoute
  '/rework-scrap': typeof ReworkScrapRoute
  '/certificates/$number': typeof CertificatesNumberRoute
  '/work-orders/new': typeof WorkOrdersNewRoute
  '/certificates': typeof CertificatesIndexRoute
  '/work-orders': typeof WorkOrdersIndexRoute
  '/work-orders/$id/bom': typeof WorkOrdersIdBomRoute
  '/work-orders/$id/confirmation': typeof WorkOrdersIdConfirmationRoute
  '/work-orders/$id/consumption': typeof WorkOrdersIdConsumptionRoute
  '/work-orders/$id/edit': typeof WorkOrdersIdEditRoute
  '/work-orders/$id/quality': typeof WorkOrdersIdQualityRoute
  '/work-orders/$id/stages': typeof WorkOrdersIdStagesRoute
  '/work-orders/$id': typeof WorkOrdersIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/exceptions': typeof ExceptionsRoute
  '/finished-goods': typeof FinishedGoodsRoute
  '/login': typeof LoginRoute
  '/rework-scrap': typeof ReworkScrapRoute
  '/certificates/$number': typeof CertificatesNumberRoute
  '/work-orders/$id': typeof WorkOrdersIdRouteWithChildren
  '/work-orders/new': typeof WorkOrdersNewRoute
  '/certificates/': typeof CertificatesIndexRoute
  '/work-orders/': typeof WorkOrdersIndexRoute
  '/work-orders/$id/bom': typeof WorkOrdersIdBomRoute
  '/work-orders/$id/confirmation': typeof WorkOrdersIdConfirmationRoute
  '/work-orders/$id/consumption': typeof WorkOrdersIdConsumptionRoute
  '/work-orders/$id/edit': typeof WorkOrdersIdEditRoute
  '/work-orders/$id/quality': typeof WorkOrdersIdQualityRoute
  '/work-orders/$id/stages': typeof WorkOrdersIdStagesRoute
  '/work-orders/$id/': typeof WorkOrdersIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/exceptions'
    | '/finished-goods'
    | '/login'
    | '/rework-scrap'
    | '/certificates/$number'
    | '/work-orders/$id'
    | '/work-orders/new'
    | '/certificates/'
    | '/work-orders/'
    | '/work-orders/$id/bom'
    | '/work-orders/$id/confirmation'
    | '/work-orders/$id/consumption'
    | '/work-orders/$id/edit'
    | '/work-orders/$id/quality'
    | '/work-orders/$id/stages'
    | '/work-orders/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/exceptions'
    | '/finished-goods'
    | '/login'
    | '/rework-scrap'
    | '/certificates/$number'
    | '/work-orders/new'
    | '/certificates'
    | '/work-orders'
    | '/work-orders/$id/bom'
    | '/work-orders/$id/confirmation'
    | '/work-orders/$id/consumption'
    | '/work-orders/$id/edit'
    | '/work-orders/$id/quality'
    | '/work-orders/$id/stages'
    | '/work-orders/$id'
  id:
    | '__root__'
    | '/'
    | '/exceptions'
    | '/finished-goods'
    | '/login'
    | '/rework-scrap'
    | '/certificates/$number'
    | '/work-orders/$id'
    | '/work-orders/new'
    | '/certificates/'
    | '/work-orders/'
    | '/work-orders/$id/bom'
    | '/work-orders/$id/confirmation'
    | '/work-orders/$id/consumption'
    | '/work-orders/$id/edit'
    | '/work-orders/$id/quality'
    | '/work-orders/$id/stages'
    | '/work-orders/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExceptionsRoute: typeof ExceptionsRoute
  FinishedGoodsRoute: typeof FinishedGoodsRoute
  LoginRoute: typeof LoginRoute
  ReworkScrapRoute: typeof ReworkScrapRoute
  CertificatesNumberRoute: typeof CertificatesNumberRoute
  WorkOrdersIdRoute: typeof WorkOrdersIdRouteWithChildren
  WorkOrdersNewRoute: typeof WorkOrdersNewRoute
  CertificatesIndexRoute: typeof CertificatesIndexRoute
  WorkOrdersIndexRoute: typeof WorkOrdersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exceptions': {
      id: '/exceptions'
      path: '/exceptions'
      fullPath: '/exceptions'
      preLoaderRoute: typeof ExceptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finished-goods': {
      id: '/finished-goods'
      path: '/finished-goods'
      fullPath: '/finished-goods'
      preLoaderRoute: typeof FinishedGoodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rework-scrap': {
      id: '/rework-scrap'
      path: '/rework-scrap'
      fullPath: '/rework-scrap'
      preLoaderRoute: typeof ReworkScrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates/': {
      id: '/certificates/'
      path: '/certificates'
      fullPath: '/certificates/'
      preLoaderRoute: typeof CertificatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates/$number': {
      id: '/certificates/$number'
      path: '/certificates/$number'
      fullPath: '/certificates/$number'
      preLoaderRoute: typeof CertificatesNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work-orders/': {
      id: '/work-orders/'
      path: '/work-orders'
      fullPath: '/work-orders/'
      preLoaderRoute: typeof WorkOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work-orders/$id': {
      id: '/work-orders/$id'
      path: '/work-orders/$id'
      fullPath: '/work-orders/$id'
      preLoaderRoute: typeof WorkOrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work-orders/new': {
      id: '/work-orders/new'
      path: '/work-orders/new'
      fullPath: '/work-orders/new'
      preLoaderRoute: typeof WorkOrdersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work-orders/$id/': {
      id: '/work-orders/$id/'
      path: '/'
      fullPath: '/work-orders/$id/'
      preLoaderRoute: typeof WorkOrdersIdIndexRouteImport
      parentRoute: typeof WorkOrdersIdRoute
    }
    '/work-orders/$id/bom': {
      id: '/work-orders/$id/bom'
      path: '/bom'
      fullPath: '/work-orders/$id/bom'
      preLoaderRoute: typeof WorkOrdersIdBomRouteImport
      parentRoute: typeof WorkOrdersIdRoute
    }
    '/work-orders/$id/confirmation': {
      id: '/work-orders/$id/confirmation'
      path: '/confirmation'
      fullPath: '/work-orders/$id/confirmation'
      preLoaderRoute: typeof WorkOrdersIdConfirmationRouteImport
      parentRoute: typeof WorkOrdersIdRoute
    }
    '/work-orders/$id/consumption': {
      id: '/work-orders/$id/consumption'
      path: '/consumption'
      fullPath: '/work-orders/$id/consumption'
      preLoaderRoute: typeof WorkOrdersIdConsumptionRouteImport
      parentRoute: typeof WorkOrdersIdRoute
    }
    '/work-orders/$id/edit': {
      id: '/work-orders/$id/edit'
      path: '/edit'
      fullPath: '/work-orders/$id/edit'
      preLoaderRoute: typeof WorkOrdersIdEditRouteImport
      parentRoute: typeof WorkOrdersIdRoute
    }
    '/work-orders/$id/quality': {
      id: '/work-orders/$id/quality'
      path: '/quality'
      fullPath: '/work-orders/$id/quality'
      preLoaderRoute: typeof WorkOrdersIdQualityRouteImport
      parentRoute: typeof WorkOrdersIdRoute
    }
    '/work-orders/$id/stages': {
      id: '/work-orders/$id/stages'
      path: '/stages'
      fullPath: '/work-orders/$id/stages'
      preLoaderRoute: typeof WorkOrdersIdStagesRouteImport
      parentRoute: typeof WorkOrdersIdRoute
    }
  }
}

interface WorkOrdersIdRouteChildren {
  WorkOrdersIdBomRoute: typeof WorkOrdersIdBomRoute
  WorkOrdersIdConfirmationRoute: typeof WorkOrdersIdConfirmationRoute
  WorkOrdersIdConsumptionRoute: typeof WorkOrdersIdConsumptionRoute
  WorkOrdersIdEditRoute: typeof WorkOrdersIdEditRoute
  WorkOrdersIdQualityRoute: typeof WorkOrdersIdQualityRoute
  WorkOrdersIdStagesRoute: typeof WorkOrdersIdStagesRoute
  WorkOrdersIdIndexRoute: typeof WorkOrdersIdIndexRoute
}

const WorkOrdersIdRouteChildren: WorkOrdersIdRouteChildren = {
  WorkOrdersIdBomRoute: WorkOrdersIdBomRoute,
  WorkOrdersIdConfirmationRoute: WorkOrdersIdConfirmationRoute,
  WorkOrdersIdConsumptionRoute: WorkOrdersIdConsumptionRoute,
  WorkOrdersIdEditRoute: WorkOrdersIdEditRoute,
  WorkOrdersIdQualityRoute: WorkOrdersIdQualityRoute,
  WorkOrdersIdStagesRoute: WorkOrdersIdStagesRoute,
  WorkOrdersIdIndexRoute: WorkOrdersIdIndexRoute,
}

const WorkOrdersIdRouteWithChildren = WorkOrdersIdRoute._addFileChildren(
  WorkOrdersIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExceptionsRoute: ExceptionsRoute,
  FinishedGoodsRoute: FinishedGoodsRoute,
  LoginRoute: LoginRoute,
  ReworkScrapRoute: ReworkScrapRoute,
  CertificatesNumberRoute: CertificatesNumberRoute,
  WorkOrdersIdRoute: WorkOrdersIdRouteWithChildren,
  WorkOrdersNewRoute: WorkOrdersNewRoute,
  CertificatesIndexRoute: CertificatesIndexRoute,
  WorkOrdersIndexRoute: WorkOrdersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
