/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcceptArrivalRouteImport } from './routes/accept-arrival'
import { Route as ArrivalSuccessRouteImport } from './routes/arrival-success'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DockAssignmentRouteImport } from './routes/dock-assignment'
import { Route as DriverVerificationRouteImport } from './routes/driver-verification'
import { Route as EmployeesRouteImport } from './routes/employees'
import { Route as GateEntryRouteImport } from './routes/gate-entry'
import { Route as GrnRouteImport } from './routes/grn'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MasterCoreRouteImport } from './routes/master-core'
import { Route as MasterDataRouteImport } from './routes/master-data'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PurchaseOrderRouteImport } from './routes/purchase-order'
import { Route as ReceivingRouteImport } from './routes/receiving'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as VehicleQueueRouteImport } from './routes/vehicle-queue'
import { Route as VehicleVerificationRouteImport } from './routes/vehicle-verification'
import { Route as WaveFlowRouteImport } from './routes/wave-flow'
import { Route as WorkCraftRouteImport } from './routes/work-craft'
import { Route as MasterCoreIndexRouteImport } from './routes/master-core.index'
import { Route as MasterCoreEmployeesRouteImport } from './routes/master-core.employees'
import { Route as MasterCoreGeographyRouteImport } from './routes/master-core.geography'
import { Route as MasterCoreHelpRouteImport } from './routes/master-core.help'
import { Route as MasterCoreSettingsRouteImport } from './routes/master-core.settings'
import { Route as MasterCoreVehiclesRouteImport } from './routes/master-core.vehicles'
import { Route as MasterCoreWarehousesRouteImport } from './routes/master-core.warehouses'
import { Route as WaveFlowIndexRouteImport } from './routes/wave-flow.index'
import { Route as WaveFlowAllocationRouteImport } from './routes/wave-flow.allocation'
import { Route as WaveFlowBackordersRouteImport } from './routes/wave-flow.backorders'
import { Route as WaveFlowDispatchRouteImport } from './routes/wave-flow.dispatch'
import { Route as WaveFlowLoadVerificationRouteImport } from './routes/wave-flow.load-verification'
import { Route as WaveFlowLoadingRouteImport } from './routes/wave-flow.loading'
import { Route as WaveFlowPackingRouteImport } from './routes/wave-flow.packing'
import { Route as WaveFlowPickListsRouteImport } from './routes/wave-flow.pick-lists'
import { Route as WaveFlowPickingRouteImport } from './routes/wave-flow.picking'
import { Route as WaveFlowReportsRouteImport } from './routes/wave-flow.reports'
import { Route as WaveFlowSalesOrdersRouteImport } from './routes/wave-flow.sales-orders'
import { Route as WaveFlowSettingsRouteImport } from './routes/wave-flow.settings'
import { Route as WaveFlowShippingRouteImport } from './routes/wave-flow.shipping'
import { Route as WaveFlowShippingLabelsRouteImport } from './routes/wave-flow.shipping-labels'
import { Route as WaveFlowStagingRouteImport } from './routes/wave-flow.staging'
import { Route as WaveFlowWavePlanningRouteImport } from './routes/wave-flow.wave-planning'
import { Route as WaveFlowWaveReleaseRouteImport } from './routes/wave-flow.wave-release'
import { Route as WorkCraftIndexRouteImport } from './routes/work-craft.index'
import { Route as WorkCraftExceptionsRouteImport } from './routes/work-craft.exceptions'
import { Route as WorkCraftFinishedGoodsRouteImport } from './routes/work-craft.finished-goods'
import { Route as WorkCraftReworkScrapRouteImport } from './routes/work-craft.rework-scrap'
import { Route as MasterCoreCustomersIndexRouteImport } from './routes/master-core.customers.index'
import { Route as MasterCoreCustomersIdRouteImport } from './routes/master-core.customers.$id'
import { Route as MasterCoreItemsIndexRouteImport } from './routes/master-core.items.index'
import { Route as MasterCoreItemsIdRouteImport } from './routes/master-core.items.$id'
import { Route as MasterCoreSuppliersIndexRouteImport } from './routes/master-core.suppliers.index'
import { Route as MasterCoreSuppliersIdRouteImport } from './routes/master-core.suppliers.$id'
import { Route as WorkCraftCertificatesIndexRouteImport } from './routes/work-craft.certificates.index'
import { Route as WorkCraftCertificatesNumberRouteImport } from './routes/work-craft.certificates.$number'
import { Route as WorkCraftWorkOrdersIndexRouteImport } from './routes/work-craft.work-orders.index'
import { Route as WorkCraftWorkOrdersIdRouteImport } from './routes/work-craft.work-orders.$id'
import { Route as WorkCraftWorkOrdersNewRouteImport } from './routes/work-craft.work-orders.new'
import { Route as WorkCraftWorkOrdersIdIndexRouteImport } from './routes/work-craft.work-orders.$id.index'
import { Route as WorkCraftWorkOrdersIdBomRouteImport } from './routes/work-craft.work-orders.$id.bom'
import { Route as WorkCraftWorkOrdersIdConfirmationRouteImport } from './routes/work-craft.work-orders.$id.confirmation'
import { Route as WorkCraftWorkOrdersIdConsumptionRouteImport } from './routes/work-craft.work-orders.$id.consumption'
import { Route as WorkCraftWorkOrdersIdEditRouteImport } from './routes/work-craft.work-orders.$id.edit'
import { Route as WorkCraftWorkOrdersIdQualityRouteImport } from './routes/work-craft.work-orders.$id.quality'
import { Route as WorkCraftWorkOrdersIdStagesRouteImport } from './routes/work-craft.work-orders.$id.stages'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptArrivalRoute = AcceptArrivalRouteImport.update({
  id: '/accept-arrival',
  path: '/accept-arrival',
  getParentRoute: () => rootRouteImport,
} as any)
const ArrivalSuccessRoute = ArrivalSuccessRouteImport.update({
  id: '/arrival-success',
  path: '/arrival-success',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DockAssignmentRoute = DockAssignmentRouteImport.update({
  id: '/dock-assignment',
  path: '/dock-assignment',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverVerificationRoute = DriverVerificationRouteImport.update({
  id: '/driver-verification',
  path: '/driver-verification',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesRoute = EmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const GateEntryRoute = GateEntryRouteImport.update({
  id: '/gate-entry',
  path: '/gate-entry',
  getParentRoute: () => rootRouteImport,
} as any)
const GrnRoute = GrnRouteImport.update({
  id: '/grn',
  path: '/grn',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterCoreRoute = MasterCoreRouteImport.update({
  id: '/master-core',
  path: '/master-core',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterDataRoute = MasterDataRouteImport.update({
  id: '/master-data',
  path: '/master-data',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseOrderRoute = PurchaseOrderRouteImport.update({
  id: '/purchase-order',
  path: '/purchase-order',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceivingRoute = ReceivingRouteImport.update({
  id: '/receiving',
  path: '/receiving',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const VehicleQueueRoute = VehicleQueueRouteImport.update({
  id: '/vehicle-queue',
  path: '/vehicle-queue',
  getParentRoute: () => rootRouteImport,
} as any)
const VehicleVerificationRoute = VehicleVerificationRouteImport.update({
  id: '/vehicle-verification',
  path: '/vehicle-verification',
  getParentRoute: () => rootRouteImport,
} as any)
const WaveFlowRoute = WaveFlowRouteImport.update({
  id: '/wave-flow',
  path: '/wave-flow',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkCraftRoute = WorkCraftRouteImport.update({
  id: '/work-craft',
  path: '/work-craft',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterCoreIndexRoute = MasterCoreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MasterCoreRoute,
} as any)
const MasterCoreEmployeesRoute = MasterCoreEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => MasterCoreRoute,
} as any)
const MasterCoreGeographyRoute = MasterCoreGeographyRouteImport.update({
  id: '/geography',
  path: '/geography',
  getParentRoute: () => MasterCoreRoute,
} as any)
const MasterCoreHelpRoute = MasterCoreHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => MasterCoreRoute,
} as any)
const MasterCoreSettingsRoute = MasterCoreSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => MasterCoreRoute,
} as any)
const MasterCoreVehiclesRoute = MasterCoreVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => MasterCoreRoute,
} as any)
const MasterCoreWarehousesRoute = MasterCoreWarehousesRouteImport.update({
  id: '/warehouses',
  path: '/warehouses',
  getParentRoute: () => MasterCoreRoute,
} as any)
const WaveFlowIndexRoute = WaveFlowIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WaveFlowRoute,
} as any)
const WaveFlowAllocationRoute = WaveFlowAllocationRouteImport.update({
  id: '/allocation',
  path: '/allocation',
  getParentRoute: () => WaveFlowRoute,
} as any)
const WaveFlowBackordersRoute = WaveFlowBackordersRouteImport.update({
  id: '/backorders',
  path: '/backorders',
  getParentRoute: () => WaveFlowRoute,
} as any)
const WaveFlowDispatchRoute = WaveFlowDispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => WaveFlowRoute,
} as any)
const WaveFlowLoadVerificationRoute =
  WaveFlowLoadVerificationRouteImport.update({
    id: '/load-verification',
    path: '/load-verification',
    getParentRoute: () => WaveFlowRoute,
  } as any)
const WaveFlowLoadingRoute = WaveFlowLoadingRouteImport.update({
  id: '/loading',
  path: '/loading',
  getParentRoute: () => WaveFlowRoute,
} as any)
const WaveFlowPackingRoute = WaveFlowPackingRouteImport.update({
  id: '/packing',
  path: '/packing',
  getParentRoute: () => WaveFlowRoute,
} as any)
const WaveFlowPickListsRoute = WaveFlowPickListsRouteImport.update({
  id: '/pick-lists',
  path: '/pick-lists',
  getParentRoute: () => WaveFlowRoute,
} as any)
const WaveFlowPickingRoute = WaveFlowPickingRouteImport.update({
  id: '/picking',
  path: '/picking',
  getParentRoute: () => WaveFlowRoute,
} as any)
const WaveFlowReportsRoute = WaveFlowReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => WaveFlowRoute,
} as any)
const WaveFlowSalesOrdersRoute = WaveFlowSalesOrdersRouteImport.update({
  id: '/sales-orders',
  path: '/sales-orders',
  getParentRoute: () => WaveFlowRoute,
} as any)
const WaveFlowSettingsRoute = WaveFlowSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => WaveFlowRoute,
} as any)
const WaveFlowShippingRoute = WaveFlowShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => WaveFlowRoute,
} as any)
const WaveFlowShippingLabelsRoute = WaveFlowShippingLabelsRouteImport.update({
  id: '/shipping-labels',
  path: '/shipping-labels',
  getParentRoute: () => WaveFlowRoute,
} as any)
const WaveFlowStagingRoute = WaveFlowStagingRouteImport.update({
  id: '/staging',
  path: '/staging',
  getParentRoute: () => WaveFlowRoute,
} as any)
const WaveFlowWavePlanningRoute = WaveFlowWavePlanningRouteImport.update({
  id: '/wave-planning',
  path: '/wave-planning',
  getParentRoute: () => WaveFlowRoute,
} as any)
const WaveFlowWaveReleaseRoute = WaveFlowWaveReleaseRouteImport.update({
  id: '/wave-release',
  path: '/wave-release',
  getParentRoute: () => WaveFlowRoute,
} as any)
const WorkCraftIndexRoute = WorkCraftIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkCraftRoute,
} as any)
const WorkCraftExceptionsRoute = WorkCraftExceptionsRouteImport.update({
  id: '/exceptions',
  path: '/exceptions',
  getParentRoute: () => WorkCraftRoute,
} as any)
const WorkCraftFinishedGoodsRoute = WorkCraftFinishedGoodsRouteImport.update({
  id: '/finished-goods',
  path: '/finished-goods',
  getParentRoute: () => WorkCraftRoute,
} as any)
const WorkCraftReworkScrapRoute = WorkCraftReworkScrapRouteImport.update({
  id: '/rework-scrap',
  path: '/rework-scrap',
  getParentRoute: () => WorkCraftRoute,
} as any)
const MasterCoreCustomersIndexRoute =
  MasterCoreCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => MasterCoreRoute,
  } as any)
const MasterCoreCustomersIdRoute = MasterCoreCustomersIdRouteImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => MasterCoreRoute,
} as any)
const MasterCoreItemsIndexRoute = MasterCoreItemsIndexRouteImport.update({
  id: '/items/',
  path: '/items/',
  getParentRoute: () => MasterCoreRoute,
} as any)
const MasterCoreItemsIdRoute = MasterCoreItemsIdRouteImport.update({
  id: '/items/$id',
  path: '/items/$id',
  getParentRoute: () => MasterCoreRoute,
} as any)
const MasterCoreSuppliersIndexRoute =
  MasterCoreSuppliersIndexRouteImport.update({
    id: '/suppliers/',
    path: '/suppliers/',
    getParentRoute: () => MasterCoreRoute,
  } as any)
const MasterCoreSuppliersIdRoute = MasterCoreSuppliersIdRouteImport.update({
  id: '/suppliers/$id',
  path: '/suppliers/$id',
  getParentRoute: () => MasterCoreRoute,
} as any)
const WorkCraftCertificatesIndexRoute =
  WorkCraftCertificatesIndexRouteImport.update({
    id: '/certificates/',
    path: '/certificates/',
    getParentRoute: () => WorkCraftRoute,
  } as any)
const WorkCraftCertificatesNumberRoute =
  WorkCraftCertificatesNumberRouteImport.update({
    id: '/certificates/$number',
    path: '/certificates/$number',
    getParentRoute: () => WorkCraftRoute,
  } as any)
const WorkCraftWorkOrdersIndexRoute =
  WorkCraftWorkOrdersIndexRouteImport.update({
    id: '/work-orders/',
    path: '/work-orders/',
    getParentRoute: () => WorkCraftRoute,
  } as any)
const WorkCraftWorkOrdersIdRoute = WorkCraftWorkOrdersIdRouteImport.update({
  id: '/work-orders/$id',
  path: '/work-orders/$id',
  getParentRoute: () => WorkCraftRoute,
} as any)
const WorkCraftWorkOrdersNewRoute = WorkCraftWorkOrdersNewRouteImport.update({
  id: '/work-orders/new',
  path: '/work-orders/new',
  getParentRoute: () => WorkCraftRoute,
} as any)
const WorkCraftWorkOrdersIdIndexRoute =
  WorkCraftWorkOrdersIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkCraftWorkOrdersIdRoute,
  } as any)
const WorkCraftWorkOrdersIdBomRoute =
  WorkCraftWorkOrdersIdBomRouteImport.update({
    id: '/bom',
    path: '/bom',
    getParentRoute: () => WorkCraftWorkOrdersIdRoute,
  } as any)
const WorkCraftWorkOrdersIdConfirmationRoute =
  WorkCraftWorkOrdersIdConfirmationRouteImport.update({
    id: '/confirmation',
    path: '/confirmation',
    getParentRoute: () => WorkCraftWorkOrdersIdRoute,
  } as any)
const WorkCraftWorkOrdersIdConsumptionRoute =
  WorkCraftWorkOrdersIdConsumptionRouteImport.update({
    id: '/consumption',
    path: '/consumption',
    getParentRoute: () => WorkCraftWorkOrdersIdRoute,
  } as any)
const WorkCraftWorkOrdersIdEditRoute =
  WorkCraftWorkOrdersIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => WorkCraftWorkOrdersIdRoute,
  } as any)
const WorkCraftWorkOrdersIdQualityRoute =
  WorkCraftWorkOrdersIdQualityRouteImport.update({
    id: '/quality',
    path: '/quality',
    getParentRoute: () => WorkCraftWorkOrdersIdRoute,
  } as any)
const WorkCraftWorkOrdersIdStagesRoute =
  WorkCraftWorkOrdersIdStagesRouteImport.update({
    id: '/stages',
    path: '/stages',
    getParentRoute: () => WorkCraftWorkOrdersIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-arrival': typeof AcceptArrivalRoute
  '/arrival-success': typeof ArrivalSuccessRoute
  '/dashboard': typeof DashboardRoute
  '/dock-assignment': typeof DockAssignmentRoute
  '/driver-verification': typeof DriverVerificationRoute
  '/employees': typeof EmployeesRoute
  '/gate-entry': typeof GateEntryRoute
  '/grn': typeof GrnRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/master-core': typeof MasterCoreRouteWithChildren
  '/master-data': typeof MasterDataRoute
  '/notifications': typeof NotificationsRoute
  '/purchase-order': typeof PurchaseOrderRoute
  '/receiving': typeof ReceivingRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/vehicle-queue': typeof VehicleQueueRoute
  '/vehicle-verification': typeof VehicleVerificationRoute
  '/wave-flow': typeof WaveFlowRouteWithChildren
  '/work-craft': typeof WorkCraftRouteWithChildren
  '/master-core/employees': typeof MasterCoreEmployeesRoute
  '/master-core/geography': typeof MasterCoreGeographyRoute
  '/master-core/help': typeof MasterCoreHelpRoute
  '/master-core/settings': typeof MasterCoreSettingsRoute
  '/master-core/vehicles': typeof MasterCoreVehiclesRoute
  '/master-core/warehouses': typeof MasterCoreWarehousesRoute
  '/wave-flow/allocation': typeof WaveFlowAllocationRoute
  '/wave-flow/backorders': typeof WaveFlowBackordersRoute
  '/wave-flow/dispatch': typeof WaveFlowDispatchRoute
  '/wave-flow/load-verification': typeof WaveFlowLoadVerificationRoute
  '/wave-flow/loading': typeof WaveFlowLoadingRoute
  '/wave-flow/packing': typeof WaveFlowPackingRoute
  '/wave-flow/pick-lists': typeof WaveFlowPickListsRoute
  '/wave-flow/picking': typeof WaveFlowPickingRoute
  '/wave-flow/reports': typeof WaveFlowReportsRoute
  '/wave-flow/sales-orders': typeof WaveFlowSalesOrdersRoute
  '/wave-flow/settings': typeof WaveFlowSettingsRoute
  '/wave-flow/shipping': typeof WaveFlowShippingRoute
  '/wave-flow/shipping-labels': typeof WaveFlowShippingLabelsRoute
  '/wave-flow/staging': typeof WaveFlowStagingRoute
  '/wave-flow/wave-planning': typeof WaveFlowWavePlanningRoute
  '/wave-flow/wave-release': typeof WaveFlowWaveReleaseRoute
  '/work-craft/exceptions': typeof WorkCraftExceptionsRoute
  '/work-craft/finished-goods': typeof WorkCraftFinishedGoodsRoute
  '/work-craft/rework-scrap': typeof WorkCraftReworkScrapRoute
  '/master-core/': typeof MasterCoreIndexRoute
  '/wave-flow/': typeof WaveFlowIndexRoute
  '/work-craft/': typeof WorkCraftIndexRoute
  '/master-core/customers/$id': typeof MasterCoreCustomersIdRoute
  '/master-core/items/$id': typeof MasterCoreItemsIdRoute
  '/master-core/suppliers/$id': typeof MasterCoreSuppliersIdRoute
  '/work-craft/certificates/$number': typeof WorkCraftCertificatesNumberRoute
  '/work-craft/work-orders/$id': typeof WorkCraftWorkOrdersIdRouteWithChildren
  '/work-craft/work-orders/new': typeof WorkCraftWorkOrdersNewRoute
  '/master-core/customers/': typeof MasterCoreCustomersIndexRoute
  '/master-core/items/': typeof MasterCoreItemsIndexRoute
  '/master-core/suppliers/': typeof MasterCoreSuppliersIndexRoute
  '/work-craft/certificates/': typeof WorkCraftCertificatesIndexRoute
  '/work-craft/work-orders/': typeof WorkCraftWorkOrdersIndexRoute
  '/work-craft/work-orders/$id/bom': typeof WorkCraftWorkOrdersIdBomRoute
  '/work-craft/work-orders/$id/confirmation': typeof WorkCraftWorkOrdersIdConfirmationRoute
  '/work-craft/work-orders/$id/consumption': typeof WorkCraftWorkOrdersIdConsumptionRoute
  '/work-craft/work-orders/$id/edit': typeof WorkCraftWorkOrdersIdEditRoute
  '/work-craft/work-orders/$id/quality': typeof WorkCraftWorkOrdersIdQualityRoute
  '/work-craft/work-orders/$id/stages': typeof WorkCraftWorkOrdersIdStagesRoute
  '/work-craft/work-orders/$id/': typeof WorkCraftWorkOrdersIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-arrival': typeof AcceptArrivalRoute
  '/arrival-success': typeof ArrivalSuccessRoute
  '/dashboard': typeof DashboardRoute
  '/dock-assignment': typeof DockAssignmentRoute
  '/driver-verification': typeof DriverVerificationRoute
  '/employees': typeof EmployeesRoute
  '/gate-entry': typeof GateEntryRoute
  '/grn': typeof GrnRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/master-data': typeof MasterDataRoute
  '/notifications': typeof NotificationsRoute
  '/purchase-order': typeof PurchaseOrderRoute
  '/receiving': typeof ReceivingRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/vehicle-queue': typeof VehicleQueueRoute
  '/vehicle-verification': typeof VehicleVerificationRoute
  '/master-core/employees': typeof MasterCoreEmployeesRoute
  '/master-core/geography': typeof MasterCoreGeographyRoute
  '/master-core/help': typeof MasterCoreHelpRoute
  '/master-core/settings': typeof MasterCoreSettingsRoute
  '/master-core/vehicles': typeof MasterCoreVehiclesRoute
  '/master-core/warehouses': typeof MasterCoreWarehousesRoute
  '/wave-flow/allocation': typeof WaveFlowAllocationRoute
  '/wave-flow/backorders': typeof WaveFlowBackordersRoute
  '/wave-flow/dispatch': typeof WaveFlowDispatchRoute
  '/wave-flow/load-verification': typeof WaveFlowLoadVerificationRoute
  '/wave-flow/loading': typeof WaveFlowLoadingRoute
  '/wave-flow/packing': typeof WaveFlowPackingRoute
  '/wave-flow/pick-lists': typeof WaveFlowPickListsRoute
  '/wave-flow/picking': typeof WaveFlowPickingRoute
  '/wave-flow/reports': typeof WaveFlowReportsRoute
  '/wave-flow/sales-orders': typeof WaveFlowSalesOrdersRoute
  '/wave-flow/settings': typeof WaveFlowSettingsRoute
  '/wave-flow/shipping': typeof WaveFlowShippingRoute
  '/wave-flow/shipping-labels': typeof WaveFlowShippingLabelsRoute
  '/wave-flow/staging': typeof WaveFlowStagingRoute
  '/wave-flow/wave-planning': typeof WaveFlowWavePlanningRoute
  '/wave-flow/wave-release': typeof WaveFlowWaveReleaseRoute
  '/work-craft/exceptions': typeof WorkCraftExceptionsRoute
  '/work-craft/finished-goods': typeof WorkCraftFinishedGoodsRoute
  '/work-craft/rework-scrap': typeof WorkCraftReworkScrapRoute
  '/master-core': typeof MasterCoreIndexRoute
  '/wave-flow': typeof WaveFlowIndexRoute
  '/work-craft': typeof WorkCraftIndexRoute
  '/master-core/customers/$id': typeof MasterCoreCustomersIdRoute
  '/master-core/items/$id': typeof MasterCoreItemsIdRoute
  '/master-core/suppliers/$id': typeof MasterCoreSuppliersIdRoute
  '/work-craft/certificates/$number': typeof WorkCraftCertificatesNumberRoute
  '/work-craft/work-orders/new': typeof WorkCraftWorkOrdersNewRoute
  '/master-core/customers': typeof MasterCoreCustomersIndexRoute
  '/master-core/items': typeof MasterCoreItemsIndexRoute
  '/master-core/suppliers': typeof MasterCoreSuppliersIndexRoute
  '/work-craft/certificates': typeof WorkCraftCertificatesIndexRoute
  '/work-craft/work-orders': typeof WorkCraftWorkOrdersIndexRoute
  '/work-craft/work-orders/$id/bom': typeof WorkCraftWorkOrdersIdBomRoute
  '/work-craft/work-orders/$id/confirmation': typeof WorkCraftWorkOrdersIdConfirmationRoute
  '/work-craft/work-orders/$id/consumption': typeof WorkCraftWorkOrdersIdConsumptionRoute
  '/work-craft/work-orders/$id/edit': typeof WorkCraftWorkOrdersIdEditRoute
  '/work-craft/work-orders/$id/quality': typeof WorkCraftWorkOrdersIdQualityRoute
  '/work-craft/work-orders/$id/stages': typeof WorkCraftWorkOrdersIdStagesRoute
  '/work-craft/work-orders/$id': typeof WorkCraftWorkOrdersIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accept-arrival': typeof AcceptArrivalRoute
  '/arrival-success': typeof ArrivalSuccessRoute
  '/dashboard': typeof DashboardRoute
  '/dock-assignment': typeof DockAssignmentRoute
  '/driver-verification': typeof DriverVerificationRoute
  '/employees': typeof EmployeesRoute
  '/gate-entry': typeof GateEntryRoute
  '/grn': typeof GrnRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/master-core': typeof MasterCoreRouteWithChildren
  '/master-data': typeof MasterDataRoute
  '/notifications': typeof NotificationsRoute
  '/purchase-order': typeof PurchaseOrderRoute
  '/receiving': typeof ReceivingRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/vehicle-queue': typeof VehicleQueueRoute
  '/vehicle-verification': typeof VehicleVerificationRoute
  '/wave-flow': typeof WaveFlowRouteWithChildren
  '/work-craft': typeof WorkCraftRouteWithChildren
  '/master-core/employees': typeof MasterCoreEmployeesRoute
  '/master-core/geography': typeof MasterCoreGeographyRoute
  '/master-core/help': typeof MasterCoreHelpRoute
  '/master-core/settings': typeof MasterCoreSettingsRoute
  '/master-core/vehicles': typeof MasterCoreVehiclesRoute
  '/master-core/warehouses': typeof MasterCoreWarehousesRoute
  '/wave-flow/allocation': typeof WaveFlowAllocationRoute
  '/wave-flow/backorders': typeof WaveFlowBackordersRoute
  '/wave-flow/dispatch': typeof WaveFlowDispatchRoute
  '/wave-flow/load-verification': typeof WaveFlowLoadVerificationRoute
  '/wave-flow/loading': typeof WaveFlowLoadingRoute
  '/wave-flow/packing': typeof WaveFlowPackingRoute
  '/wave-flow/pick-lists': typeof WaveFlowPickListsRoute
  '/wave-flow/picking': typeof WaveFlowPickingRoute
  '/wave-flow/reports': typeof WaveFlowReportsRoute
  '/wave-flow/sales-orders': typeof WaveFlowSalesOrdersRoute
  '/wave-flow/settings': typeof WaveFlowSettingsRoute
  '/wave-flow/shipping': typeof WaveFlowShippingRoute
  '/wave-flow/shipping-labels': typeof WaveFlowShippingLabelsRoute
  '/wave-flow/staging': typeof WaveFlowStagingRoute
  '/wave-flow/wave-planning': typeof WaveFlowWavePlanningRoute
  '/wave-flow/wave-release': typeof WaveFlowWaveReleaseRoute
  '/work-craft/exceptions': typeof WorkCraftExceptionsRoute
  '/work-craft/finished-goods': typeof WorkCraftFinishedGoodsRoute
  '/work-craft/rework-scrap': typeof WorkCraftReworkScrapRoute
  '/master-core/': typeof MasterCoreIndexRoute
  '/wave-flow/': typeof WaveFlowIndexRoute
  '/work-craft/': typeof WorkCraftIndexRoute
  '/master-core/customers/$id': typeof MasterCoreCustomersIdRoute
  '/master-core/items/$id': typeof MasterCoreItemsIdRoute
  '/master-core/suppliers/$id': typeof MasterCoreSuppliersIdRoute
  '/work-craft/certificates/$number': typeof WorkCraftCertificatesNumberRoute
  '/work-craft/work-orders/$id': typeof WorkCraftWorkOrdersIdRouteWithChildren
  '/work-craft/work-orders/new': typeof WorkCraftWorkOrdersNewRoute
  '/master-core/customers/': typeof MasterCoreCustomersIndexRoute
  '/master-core/items/': typeof MasterCoreItemsIndexRoute
  '/master-core/suppliers/': typeof MasterCoreSuppliersIndexRoute
  '/work-craft/certificates/': typeof WorkCraftCertificatesIndexRoute
  '/work-craft/work-orders/': typeof WorkCraftWorkOrdersIndexRoute
  '/work-craft/work-orders/$id/bom': typeof WorkCraftWorkOrdersIdBomRoute
  '/work-craft/work-orders/$id/confirmation': typeof WorkCraftWorkOrdersIdConfirmationRoute
  '/work-craft/work-orders/$id/consumption': typeof WorkCraftWorkOrdersIdConsumptionRoute
  '/work-craft/work-orders/$id/edit': typeof WorkCraftWorkOrdersIdEditRoute
  '/work-craft/work-orders/$id/quality': typeof WorkCraftWorkOrdersIdQualityRoute
  '/work-craft/work-orders/$id/stages': typeof WorkCraftWorkOrdersIdStagesRoute
  '/work-craft/work-orders/$id/': typeof WorkCraftWorkOrdersIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-arrival'
    | '/arrival-success'
    | '/dashboard'
    | '/dock-assignment'
    | '/driver-verification'
    | '/employees'
    | '/gate-entry'
    | '/grn'
    | '/inventory'
    | '/login'
    | '/master-core'
    | '/master-data'
    | '/notifications'
    | '/purchase-order'
    | '/receiving'
    | '/reports'
    | '/settings'
    | '/vehicle-queue'
    | '/vehicle-verification'
    | '/wave-flow'
    | '/work-craft'
    | '/master-core/employees'
    | '/master-core/geography'
    | '/master-core/help'
    | '/master-core/settings'
    | '/master-core/vehicles'
    | '/master-core/warehouses'
    | '/wave-flow/allocation'
    | '/wave-flow/backorders'
    | '/wave-flow/dispatch'
    | '/wave-flow/load-verification'
    | '/wave-flow/loading'
    | '/wave-flow/packing'
    | '/wave-flow/pick-lists'
    | '/wave-flow/picking'
    | '/wave-flow/reports'
    | '/wave-flow/sales-orders'
    | '/wave-flow/settings'
    | '/wave-flow/shipping'
    | '/wave-flow/shipping-labels'
    | '/wave-flow/staging'
    | '/wave-flow/wave-planning'
    | '/wave-flow/wave-release'
    | '/work-craft/exceptions'
    | '/work-craft/finished-goods'
    | '/work-craft/rework-scrap'
    | '/master-core/'
    | '/wave-flow/'
    | '/work-craft/'
    | '/master-core/customers/$id'
    | '/master-core/items/$id'
    | '/master-core/suppliers/$id'
    | '/work-craft/certificates/$number'
    | '/work-craft/work-orders/$id'
    | '/work-craft/work-orders/new'
    | '/master-core/customers/'
    | '/master-core/items/'
    | '/master-core/suppliers/'
    | '/work-craft/certificates/'
    | '/work-craft/work-orders/'
    | '/work-craft/work-orders/$id/bom'
    | '/work-craft/work-orders/$id/confirmation'
    | '/work-craft/work-orders/$id/consumption'
    | '/work-craft/work-orders/$id/edit'
    | '/work-craft/work-orders/$id/quality'
    | '/work-craft/work-orders/$id/stages'
    | '/work-craft/work-orders/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-arrival'
    | '/arrival-success'
    | '/dashboard'
    | '/dock-assignment'
    | '/driver-verification'
    | '/employees'
    | '/gate-entry'
    | '/grn'
    | '/inventory'
    | '/login'
    | '/master-data'
    | '/notifications'
    | '/purchase-order'
    | '/receiving'
    | '/reports'
    | '/settings'
    | '/vehicle-queue'
    | '/vehicle-verification'
    | '/master-core/employees'
    | '/master-core/geography'
    | '/master-core/help'
    | '/master-core/settings'
    | '/master-core/vehicles'
    | '/master-core/warehouses'
    | '/wave-flow/allocation'
    | '/wave-flow/backorders'
    | '/wave-flow/dispatch'
    | '/wave-flow/load-verification'
    | '/wave-flow/loading'
    | '/wave-flow/packing'
    | '/wave-flow/pick-lists'
    | '/wave-flow/picking'
    | '/wave-flow/reports'
    | '/wave-flow/sales-orders'
    | '/wave-flow/settings'
    | '/wave-flow/shipping'
    | '/wave-flow/shipping-labels'
    | '/wave-flow/staging'
    | '/wave-flow/wave-planning'
    | '/wave-flow/wave-release'
    | '/work-craft/exceptions'
    | '/work-craft/finished-goods'
    | '/work-craft/rework-scrap'
    | '/master-core'
    | '/wave-flow'
    | '/work-craft'
    | '/master-core/customers/$id'
    | '/master-core/items/$id'
    | '/master-core/suppliers/$id'
    | '/work-craft/certificates/$number'
    | '/work-craft/work-orders/new'
    | '/master-core/customers'
    | '/master-core/items'
    | '/master-core/suppliers'
    | '/work-craft/certificates'
    | '/work-craft/work-orders'
    | '/work-craft/work-orders/$id/bom'
    | '/work-craft/work-orders/$id/confirmation'
    | '/work-craft/work-orders/$id/consumption'
    | '/work-craft/work-orders/$id/edit'
    | '/work-craft/work-orders/$id/quality'
    | '/work-craft/work-orders/$id/stages'
    | '/work-craft/work-orders/$id'
  id:
    | '__root__'
    | '/'
    | '/accept-arrival'
    | '/arrival-success'
    | '/dashboard'
    | '/dock-assignment'
    | '/driver-verification'
    | '/employees'
    | '/gate-entry'
    | '/grn'
    | '/inventory'
    | '/login'
    | '/master-core'
    | '/master-data'
    | '/notifications'
    | '/purchase-order'
    | '/receiving'
    | '/reports'
    | '/settings'
    | '/vehicle-queue'
    | '/vehicle-verification'
    | '/wave-flow'
    | '/work-craft'
    | '/master-core/employees'
    | '/master-core/geography'
    | '/master-core/help'
    | '/master-core/settings'
    | '/master-core/vehicles'
    | '/master-core/warehouses'
    | '/wave-flow/allocation'
    | '/wave-flow/backorders'
    | '/wave-flow/dispatch'
    | '/wave-flow/load-verification'
    | '/wave-flow/loading'
    | '/wave-flow/packing'
    | '/wave-flow/pick-lists'
    | '/wave-flow/picking'
    | '/wave-flow/reports'
    | '/wave-flow/sales-orders'
    | '/wave-flow/settings'
    | '/wave-flow/shipping'
    | '/wave-flow/shipping-labels'
    | '/wave-flow/staging'
    | '/wave-flow/wave-planning'
    | '/wave-flow/wave-release'
    | '/work-craft/exceptions'
    | '/work-craft/finished-goods'
    | '/work-craft/rework-scrap'
    | '/master-core/'
    | '/wave-flow/'
    | '/work-craft/'
    | '/master-core/customers/$id'
    | '/master-core/items/$id'
    | '/master-core/suppliers/$id'
    | '/work-craft/certificates/$number'
    | '/work-craft/work-orders/$id'
    | '/work-craft/work-orders/new'
    | '/master-core/customers/'
    | '/master-core/items/'
    | '/master-core/suppliers/'
    | '/work-craft/certificates/'
    | '/work-craft/work-orders/'
    | '/work-craft/work-orders/$id/bom'
    | '/work-craft/work-orders/$id/confirmation'
    | '/work-craft/work-orders/$id/consumption'
    | '/work-craft/work-orders/$id/edit'
    | '/work-craft/work-orders/$id/quality'
    | '/work-craft/work-orders/$id/stages'
    | '/work-craft/work-orders/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcceptArrivalRoute: typeof AcceptArrivalRoute
  ArrivalSuccessRoute: typeof ArrivalSuccessRoute
  DashboardRoute: typeof DashboardRoute
  DockAssignmentRoute: typeof DockAssignmentRoute
  DriverVerificationRoute: typeof DriverVerificationRoute
  EmployeesRoute: typeof EmployeesRoute
  GateEntryRoute: typeof GateEntryRoute
  GrnRoute: typeof GrnRoute
  InventoryRoute: typeof InventoryRoute
  LoginRoute: typeof LoginRoute
  MasterCoreRoute: typeof MasterCoreRouteWithChildren
  MasterDataRoute: typeof MasterDataRoute
  NotificationsRoute: typeof NotificationsRoute
  PurchaseOrderRoute: typeof PurchaseOrderRoute
  ReceivingRoute: typeof ReceivingRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  VehicleQueueRoute: typeof VehicleQueueRoute
  VehicleVerificationRoute: typeof VehicleVerificationRoute
  WaveFlowRoute: typeof WaveFlowRouteWithChildren
  WorkCraftRoute: typeof WorkCraftRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-arrival': {
      id: '/accept-arrival'
      path: '/accept-arrival'
      fullPath: '/accept-arrival'
      preLoaderRoute: typeof AcceptArrivalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arrival-success': {
      id: '/arrival-success'
      path: '/arrival-success'
      fullPath: '/arrival-success'
      preLoaderRoute: typeof ArrivalSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dock-assignment': {
      id: '/dock-assignment'
      path: '/dock-assignment'
      fullPath: '/dock-assignment'
      preLoaderRoute: typeof DockAssignmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver-verification': {
      id: '/driver-verification'
      path: '/driver-verification'
      fullPath: '/driver-verification'
      preLoaderRoute: typeof DriverVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gate-entry': {
      id: '/gate-entry'
      path: '/gate-entry'
      fullPath: '/gate-entry'
      preLoaderRoute: typeof GateEntryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grn': {
      id: '/grn'
      path: '/grn'
      fullPath: '/grn'
      preLoaderRoute: typeof GrnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-core': {
      id: '/master-core'
      path: '/master-core'
      fullPath: '/master-core'
      preLoaderRoute: typeof MasterCoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-data': {
      id: '/master-data'
      path: '/master-data'
      fullPath: '/master-data'
      preLoaderRoute: typeof MasterDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-order': {
      id: '/purchase-order'
      path: '/purchase-order'
      fullPath: '/purchase-order'
      preLoaderRoute: typeof PurchaseOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receiving': {
      id: '/receiving'
      path: '/receiving'
      fullPath: '/receiving'
      preLoaderRoute: typeof ReceivingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicle-queue': {
      id: '/vehicle-queue'
      path: '/vehicle-queue'
      fullPath: '/vehicle-queue'
      preLoaderRoute: typeof VehicleQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicle-verification': {
      id: '/vehicle-verification'
      path: '/vehicle-verification'
      fullPath: '/vehicle-verification'
      preLoaderRoute: typeof VehicleVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wave-flow': {
      id: '/wave-flow'
      path: '/wave-flow'
      fullPath: '/wave-flow'
      preLoaderRoute: typeof WaveFlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work-craft': {
      id: '/work-craft'
      path: '/work-craft'
      fullPath: '/work-craft'
      preLoaderRoute: typeof WorkCraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-core/': {
      id: '/master-core/'
      path: '/'
      fullPath: '/master-core/'
      preLoaderRoute: typeof MasterCoreIndexRouteImport
      parentRoute: typeof MasterCoreRoute
    }
    '/master-core/employees': {
      id: '/master-core/employees'
      path: '/employees'
      fullPath: '/master-core/employees'
      preLoaderRoute: typeof MasterCoreEmployeesRouteImport
      parentRoute: typeof MasterCoreRoute
    }
    '/master-core/geography': {
      id: '/master-core/geography'
      path: '/geography'
      fullPath: '/master-core/geography'
      preLoaderRoute: typeof MasterCoreGeographyRouteImport
      parentRoute: typeof MasterCoreRoute
    }
    '/master-core/help': {
      id: '/master-core/help'
      path: '/help'
      fullPath: '/master-core/help'
      preLoaderRoute: typeof MasterCoreHelpRouteImport
      parentRoute: typeof MasterCoreRoute
    }
    '/master-core/settings': {
      id: '/master-core/settings'
      path: '/settings'
      fullPath: '/master-core/settings'
      preLoaderRoute: typeof MasterCoreSettingsRouteImport
      parentRoute: typeof MasterCoreRoute
    }
    '/master-core/vehicles': {
      id: '/master-core/vehicles'
      path: '/vehicles'
      fullPath: '/master-core/vehicles'
      preLoaderRoute: typeof MasterCoreVehiclesRouteImport
      parentRoute: typeof MasterCoreRoute
    }
    '/master-core/warehouses': {
      id: '/master-core/warehouses'
      path: '/warehouses'
      fullPath: '/master-core/warehouses'
      preLoaderRoute: typeof MasterCoreWarehousesRouteImport
      parentRoute: typeof MasterCoreRoute
    }
    '/wave-flow/': {
      id: '/wave-flow/'
      path: '/'
      fullPath: '/wave-flow/'
      preLoaderRoute: typeof WaveFlowIndexRouteImport
      parentRoute: typeof WaveFlowRoute
    }
    '/wave-flow/allocation': {
      id: '/wave-flow/allocation'
      path: '/allocation'
      fullPath: '/wave-flow/allocation'
      preLoaderRoute: typeof WaveFlowAllocationRouteImport
      parentRoute: typeof WaveFlowRoute
    }
    '/wave-flow/backorders': {
      id: '/wave-flow/backorders'
      path: '/backorders'
      fullPath: '/wave-flow/backorders'
      preLoaderRoute: typeof WaveFlowBackordersRouteImport
      parentRoute: typeof WaveFlowRoute
    }
    '/wave-flow/dispatch': {
      id: '/wave-flow/dispatch'
      path: '/dispatch'
      fullPath: '/wave-flow/dispatch'
      preLoaderRoute: typeof WaveFlowDispatchRouteImport
      parentRoute: typeof WaveFlowRoute
    }
    '/wave-flow/load-verification': {
      id: '/wave-flow/load-verification'
      path: '/load-verification'
      fullPath: '/wave-flow/load-verification'
      preLoaderRoute: typeof WaveFlowLoadVerificationRouteImport
      parentRoute: typeof WaveFlowRoute
    }
    '/wave-flow/loading': {
      id: '/wave-flow/loading'
      path: '/loading'
      fullPath: '/wave-flow/loading'
      preLoaderRoute: typeof WaveFlowLoadingRouteImport
      parentRoute: typeof WaveFlowRoute
    }
    '/wave-flow/packing': {
      id: '/wave-flow/packing'
      path: '/packing'
      fullPath: '/wave-flow/packing'
      preLoaderRoute: typeof WaveFlowPackingRouteImport
      parentRoute: typeof WaveFlowRoute
    }
    '/wave-flow/pick-lists': {
      id: '/wave-flow/pick-lists'
      path: '/pick-lists'
      fullPath: '/wave-flow/pick-lists'
      preLoaderRoute: typeof WaveFlowPickListsRouteImport
      parentRoute: typeof WaveFlowRoute
    }
    '/wave-flow/picking': {
      id: '/wave-flow/picking'
      path: '/picking'
      fullPath: '/wave-flow/picking'
      preLoaderRoute: typeof WaveFlowPickingRouteImport
      parentRoute: typeof WaveFlowRoute
    }
    '/wave-flow/reports': {
      id: '/wave-flow/reports'
      path: '/reports'
      fullPath: '/wave-flow/reports'
      preLoaderRoute: typeof WaveFlowReportsRouteImport
      parentRoute: typeof WaveFlowRoute
    }
    '/wave-flow/sales-orders': {
      id: '/wave-flow/sales-orders'
      path: '/sales-orders'
      fullPath: '/wave-flow/sales-orders'
      preLoaderRoute: typeof WaveFlowSalesOrdersRouteImport
      parentRoute: typeof WaveFlowRoute
    }
    '/wave-flow/settings': {
      id: '/wave-flow/settings'
      path: '/settings'
      fullPath: '/wave-flow/settings'
      preLoaderRoute: typeof WaveFlowSettingsRouteImport
      parentRoute: typeof WaveFlowRoute
    }
    '/wave-flow/shipping': {
      id: '/wave-flow/shipping'
      path: '/shipping'
      fullPath: '/wave-flow/shipping'
      preLoaderRoute: typeof WaveFlowShippingRouteImport
      parentRoute: typeof WaveFlowRoute
    }
    '/wave-flow/shipping-labels': {
      id: '/wave-flow/shipping-labels'
      path: '/shipping-labels'
      fullPath: '/wave-flow/shipping-labels'
      preLoaderRoute: typeof WaveFlowShippingLabelsRouteImport
      parentRoute: typeof WaveFlowRoute
    }
    '/wave-flow/staging': {
      id: '/wave-flow/staging'
      path: '/staging'
      fullPath: '/wave-flow/staging'
      preLoaderRoute: typeof WaveFlowStagingRouteImport
      parentRoute: typeof WaveFlowRoute
    }
    '/wave-flow/wave-planning': {
      id: '/wave-flow/wave-planning'
      path: '/wave-planning'
      fullPath: '/wave-flow/wave-planning'
      preLoaderRoute: typeof WaveFlowWavePlanningRouteImport
      parentRoute: typeof WaveFlowRoute
    }
    '/wave-flow/wave-release': {
      id: '/wave-flow/wave-release'
      path: '/wave-release'
      fullPath: '/wave-flow/wave-release'
      preLoaderRoute: typeof WaveFlowWaveReleaseRouteImport
      parentRoute: typeof WaveFlowRoute
    }
    '/work-craft/': {
      id: '/work-craft/'
      path: '/'
      fullPath: '/work-craft/'
      preLoaderRoute: typeof WorkCraftIndexRouteImport
      parentRoute: typeof WorkCraftRoute
    }
    '/work-craft/exceptions': {
      id: '/work-craft/exceptions'
      path: '/exceptions'
      fullPath: '/work-craft/exceptions'
      preLoaderRoute: typeof WorkCraftExceptionsRouteImport
      parentRoute: typeof WorkCraftRoute
    }
    '/work-craft/finished-goods': {
      id: '/work-craft/finished-goods'
      path: '/finished-goods'
      fullPath: '/work-craft/finished-goods'
      preLoaderRoute: typeof WorkCraftFinishedGoodsRouteImport
      parentRoute: typeof WorkCraftRoute
    }
    '/work-craft/rework-scrap': {
      id: '/work-craft/rework-scrap'
      path: '/rework-scrap'
      fullPath: '/work-craft/rework-scrap'
      preLoaderRoute: typeof WorkCraftReworkScrapRouteImport
      parentRoute: typeof WorkCraftRoute
    }
    '/master-core/customers/': {
      id: '/master-core/customers/'
      path: '/customers'
      fullPath: '/master-core/customers/'
      preLoaderRoute: typeof MasterCoreCustomersIndexRouteImport
      parentRoute: typeof MasterCoreRoute
    }
    '/master-core/customers/$id': {
      id: '/master-core/customers/$id'
      path: '/customers/$id'
      fullPath: '/master-core/customers/$id'
      preLoaderRoute: typeof MasterCoreCustomersIdRouteImport
      parentRoute: typeof MasterCoreRoute
    }
    '/master-core/items/': {
      id: '/master-core/items/'
      path: '/items'
      fullPath: '/master-core/items/'
      preLoaderRoute: typeof MasterCoreItemsIndexRouteImport
      parentRoute: typeof MasterCoreRoute
    }
    '/master-core/items/$id': {
      id: '/master-core/items/$id'
      path: '/items/$id'
      fullPath: '/master-core/items/$id'
      preLoaderRoute: typeof MasterCoreItemsIdRouteImport
      parentRoute: typeof MasterCoreRoute
    }
    '/master-core/suppliers/': {
      id: '/master-core/suppliers/'
      path: '/suppliers'
      fullPath: '/master-core/suppliers/'
      preLoaderRoute: typeof MasterCoreSuppliersIndexRouteImport
      parentRoute: typeof MasterCoreRoute
    }
    '/master-core/suppliers/$id': {
      id: '/master-core/suppliers/$id'
      path: '/suppliers/$id'
      fullPath: '/master-core/suppliers/$id'
      preLoaderRoute: typeof MasterCoreSuppliersIdRouteImport
      parentRoute: typeof MasterCoreRoute
    }
    '/work-craft/certificates/': {
      id: '/work-craft/certificates/'
      path: '/certificates'
      fullPath: '/work-craft/certificates/'
      preLoaderRoute: typeof WorkCraftCertificatesIndexRouteImport
      parentRoute: typeof WorkCraftRoute
    }
    '/work-craft/certificates/$number': {
      id: '/work-craft/certificates/$number'
      path: '/certificates/$number'
      fullPath: '/work-craft/certificates/$number'
      preLoaderRoute: typeof WorkCraftCertificatesNumberRouteImport
      parentRoute: typeof WorkCraftRoute
    }
    '/work-craft/work-orders/': {
      id: '/work-craft/work-orders/'
      path: '/work-orders'
      fullPath: '/work-craft/work-orders/'
      preLoaderRoute: typeof WorkCraftWorkOrdersIndexRouteImport
      parentRoute: typeof WorkCraftRoute
    }
    '/work-craft/work-orders/$id': {
      id: '/work-craft/work-orders/$id'
      path: '/work-orders/$id'
      fullPath: '/work-craft/work-orders/$id'
      preLoaderRoute: typeof WorkCraftWorkOrdersIdRouteImport
      parentRoute: typeof WorkCraftRoute
    }
    '/work-craft/work-orders/new': {
      id: '/work-craft/work-orders/new'
      path: '/work-orders/new'
      fullPath: '/work-craft/work-orders/new'
      preLoaderRoute: typeof WorkCraftWorkOrdersNewRouteImport
      parentRoute: typeof WorkCraftRoute
    }
    '/work-craft/work-orders/$id/': {
      id: '/work-craft/work-orders/$id/'
      path: '/'
      fullPath: '/work-craft/work-orders/$id/'
      preLoaderRoute: typeof WorkCraftWorkOrdersIdIndexRouteImport
      parentRoute: typeof WorkCraftWorkOrdersIdRoute
    }
    '/work-craft/work-orders/$id/bom': {
      id: '/work-craft/work-orders/$id/bom'
      path: '/bom'
      fullPath: '/work-craft/work-orders/$id/bom'
      preLoaderRoute: typeof WorkCraftWorkOrdersIdBomRouteImport
      parentRoute: typeof WorkCraftWorkOrdersIdRoute
    }
    '/work-craft/work-orders/$id/confirmation': {
      id: '/work-craft/work-orders/$id/confirmation'
      path: '/confirmation'
      fullPath: '/work-craft/work-orders/$id/confirmation'
      preLoaderRoute: typeof WorkCraftWorkOrdersIdConfirmationRouteImport
      parentRoute: typeof WorkCraftWorkOrdersIdRoute
    }
    '/work-craft/work-orders/$id/consumption': {
      id: '/work-craft/work-orders/$id/consumption'
      path: '/consumption'
      fullPath: '/work-craft/work-orders/$id/consumption'
      preLoaderRoute: typeof WorkCraftWorkOrdersIdConsumptionRouteImport
      parentRoute: typeof WorkCraftWorkOrdersIdRoute
    }
    '/work-craft/work-orders/$id/edit': {
      id: '/work-craft/work-orders/$id/edit'
      path: '/edit'
      fullPath: '/work-craft/work-orders/$id/edit'
      preLoaderRoute: typeof WorkCraftWorkOrdersIdEditRouteImport
      parentRoute: typeof WorkCraftWorkOrdersIdRoute
    }
    '/work-craft/work-orders/$id/quality': {
      id: '/work-craft/work-orders/$id/quality'
      path: '/quality'
      fullPath: '/work-craft/work-orders/$id/quality'
      preLoaderRoute: typeof WorkCraftWorkOrdersIdQualityRouteImport
      parentRoute: typeof WorkCraftWorkOrdersIdRoute
    }
    '/work-craft/work-orders/$id/stages': {
      id: '/work-craft/work-orders/$id/stages'
      path: '/stages'
      fullPath: '/work-craft/work-orders/$id/stages'
      preLoaderRoute: typeof WorkCraftWorkOrdersIdStagesRouteImport
      parentRoute: typeof WorkCraftWorkOrdersIdRoute
    }
  }
}

interface MasterCoreRouteChildren {
  MasterCoreEmployeesRoute: typeof MasterCoreEmployeesRoute
  MasterCoreGeographyRoute: typeof MasterCoreGeographyRoute
  MasterCoreHelpRoute: typeof MasterCoreHelpRoute
  MasterCoreSettingsRoute: typeof MasterCoreSettingsRoute
  MasterCoreVehiclesRoute: typeof MasterCoreVehiclesRoute
  MasterCoreWarehousesRoute: typeof MasterCoreWarehousesRoute
  MasterCoreIndexRoute: typeof MasterCoreIndexRoute
  MasterCoreCustomersIdRoute: typeof MasterCoreCustomersIdRoute
  MasterCoreItemsIdRoute: typeof MasterCoreItemsIdRoute
  MasterCoreSuppliersIdRoute: typeof MasterCoreSuppliersIdRoute
  MasterCoreCustomersIndexRoute: typeof MasterCoreCustomersIndexRoute
  MasterCoreItemsIndexRoute: typeof MasterCoreItemsIndexRoute
  MasterCoreSuppliersIndexRoute: typeof MasterCoreSuppliersIndexRoute
}

const MasterCoreRouteChildren: MasterCoreRouteChildren = {
  MasterCoreEmployeesRoute: MasterCoreEmployeesRoute,
  MasterCoreGeographyRoute: MasterCoreGeographyRoute,
  MasterCoreHelpRoute: MasterCoreHelpRoute,
  MasterCoreSettingsRoute: MasterCoreSettingsRoute,
  MasterCoreVehiclesRoute: MasterCoreVehiclesRoute,
  MasterCoreWarehousesRoute: MasterCoreWarehousesRoute,
  MasterCoreIndexRoute: MasterCoreIndexRoute,
  MasterCoreCustomersIdRoute: MasterCoreCustomersIdRoute,
  MasterCoreItemsIdRoute: MasterCoreItemsIdRoute,
  MasterCoreSuppliersIdRoute: MasterCoreSuppliersIdRoute,
  MasterCoreCustomersIndexRoute: MasterCoreCustomersIndexRoute,
  MasterCoreItemsIndexRoute: MasterCoreItemsIndexRoute,
  MasterCoreSuppliersIndexRoute: MasterCoreSuppliersIndexRoute,
}

const MasterCoreRouteWithChildren = MasterCoreRoute._addFileChildren(
  MasterCoreRouteChildren,
)

interface WaveFlowRouteChildren {
  WaveFlowAllocationRoute: typeof WaveFlowAllocationRoute
  WaveFlowBackordersRoute: typeof WaveFlowBackordersRoute
  WaveFlowDispatchRoute: typeof WaveFlowDispatchRoute
  WaveFlowLoadVerificationRoute: typeof WaveFlowLoadVerificationRoute
  WaveFlowLoadingRoute: typeof WaveFlowLoadingRoute
  WaveFlowPackingRoute: typeof WaveFlowPackingRoute
  WaveFlowPickListsRoute: typeof WaveFlowPickListsRoute
  WaveFlowPickingRoute: typeof WaveFlowPickingRoute
  WaveFlowReportsRoute: typeof WaveFlowReportsRoute
  WaveFlowSalesOrdersRoute: typeof WaveFlowSalesOrdersRoute
  WaveFlowSettingsRoute: typeof WaveFlowSettingsRoute
  WaveFlowShippingRoute: typeof WaveFlowShippingRoute
  WaveFlowShippingLabelsRoute: typeof WaveFlowShippingLabelsRoute
  WaveFlowStagingRoute: typeof WaveFlowStagingRoute
  WaveFlowWavePlanningRoute: typeof WaveFlowWavePlanningRoute
  WaveFlowWaveReleaseRoute: typeof WaveFlowWaveReleaseRoute
  WaveFlowIndexRoute: typeof WaveFlowIndexRoute
}

const WaveFlowRouteChildren: WaveFlowRouteChildren = {
  WaveFlowAllocationRoute: WaveFlowAllocationRoute,
  WaveFlowBackordersRoute: WaveFlowBackordersRoute,
  WaveFlowDispatchRoute: WaveFlowDispatchRoute,
  WaveFlowLoadVerificationRoute: WaveFlowLoadVerificationRoute,
  WaveFlowLoadingRoute: WaveFlowLoadingRoute,
  WaveFlowPackingRoute: WaveFlowPackingRoute,
  WaveFlowPickListsRoute: WaveFlowPickListsRoute,
  WaveFlowPickingRoute: WaveFlowPickingRoute,
  WaveFlowReportsRoute: WaveFlowReportsRoute,
  WaveFlowSalesOrdersRoute: WaveFlowSalesOrdersRoute,
  WaveFlowSettingsRoute: WaveFlowSettingsRoute,
  WaveFlowShippingRoute: WaveFlowShippingRoute,
  WaveFlowShippingLabelsRoute: WaveFlowShippingLabelsRoute,
  WaveFlowStagingRoute: WaveFlowStagingRoute,
  WaveFlowWavePlanningRoute: WaveFlowWavePlanningRoute,
  WaveFlowWaveReleaseRoute: WaveFlowWaveReleaseRoute,
  WaveFlowIndexRoute: WaveFlowIndexRoute,
}

const WaveFlowRouteWithChildren = WaveFlowRoute._addFileChildren(
  WaveFlowRouteChildren,
)

interface WorkCraftWorkOrdersIdRouteChildren {
  WorkCraftWorkOrdersIdBomRoute: typeof WorkCraftWorkOrdersIdBomRoute
  WorkCraftWorkOrdersIdConfirmationRoute: typeof WorkCraftWorkOrdersIdConfirmationRoute
  WorkCraftWorkOrdersIdConsumptionRoute: typeof WorkCraftWorkOrdersIdConsumptionRoute
  WorkCraftWorkOrdersIdEditRoute: typeof WorkCraftWorkOrdersIdEditRoute
  WorkCraftWorkOrdersIdQualityRoute: typeof WorkCraftWorkOrdersIdQualityRoute
  WorkCraftWorkOrdersIdStagesRoute: typeof WorkCraftWorkOrdersIdStagesRoute
  WorkCraftWorkOrdersIdIndexRoute: typeof WorkCraftWorkOrdersIdIndexRoute
}

const WorkCraftWorkOrdersIdRouteChildren: WorkCraftWorkOrdersIdRouteChildren = {
  WorkCraftWorkOrdersIdBomRoute: WorkCraftWorkOrdersIdBomRoute,
  WorkCraftWorkOrdersIdConfirmationRoute:
    WorkCraftWorkOrdersIdConfirmationRoute,
  WorkCraftWorkOrdersIdConsumptionRoute: WorkCraftWorkOrdersIdConsumptionRoute,
  WorkCraftWorkOrdersIdEditRoute: WorkCraftWorkOrdersIdEditRoute,
  WorkCraftWorkOrdersIdQualityRoute: WorkCraftWorkOrdersIdQualityRoute,
  WorkCraftWorkOrdersIdStagesRoute: WorkCraftWorkOrdersIdStagesRoute,
  WorkCraftWorkOrdersIdIndexRoute: WorkCraftWorkOrdersIdIndexRoute,
}

const WorkCraftWorkOrdersIdRouteWithChildren =
  WorkCraftWorkOrdersIdRoute._addFileChildren(
    WorkCraftWorkOrdersIdRouteChildren,
  )

interface WorkCraftRouteChildren {
  WorkCraftExceptionsRoute: typeof WorkCraftExceptionsRoute
  WorkCraftFinishedGoodsRoute: typeof WorkCraftFinishedGoodsRoute
  WorkCraftReworkScrapRoute: typeof WorkCraftReworkScrapRoute
  WorkCraftIndexRoute: typeof WorkCraftIndexRoute
  WorkCraftCertificatesNumberRoute: typeof WorkCraftCertificatesNumberRoute
  WorkCraftWorkOrdersIdRoute: typeof WorkCraftWorkOrdersIdRouteWithChildren
  WorkCraftWorkOrdersNewRoute: typeof WorkCraftWorkOrdersNewRoute
  WorkCraftCertificatesIndexRoute: typeof WorkCraftCertificatesIndexRoute
  WorkCraftWorkOrdersIndexRoute: typeof WorkCraftWorkOrdersIndexRoute
}

const WorkCraftRouteChildren: WorkCraftRouteChildren = {
  WorkCraftExceptionsRoute: WorkCraftExceptionsRoute,
  WorkCraftFinishedGoodsRoute: WorkCraftFinishedGoodsRoute,
  WorkCraftReworkScrapRoute: WorkCraftReworkScrapRoute,
  WorkCraftIndexRoute: WorkCraftIndexRoute,
  WorkCraftCertificatesNumberRoute: WorkCraftCertificatesNumberRoute,
  WorkCraftWorkOrdersIdRoute: WorkCraftWorkOrdersIdRouteWithChildren,
  WorkCraftWorkOrdersNewRoute: WorkCraftWorkOrdersNewRoute,
  WorkCraftCertificatesIndexRoute: WorkCraftCertificatesIndexRoute,
  WorkCraftWorkOrdersIndexRoute: WorkCraftWorkOrdersIndexRoute,
}

const WorkCraftRouteWithChildren = WorkCraftRoute._addFileChildren(
  WorkCraftRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcceptArrivalRoute: AcceptArrivalRoute,
  ArrivalSuccessRoute: ArrivalSuccessRoute,
  DashboardRoute: DashboardRoute,
  DockAssignmentRoute: DockAssignmentRoute,
  DriverVerificationRoute: DriverVerificationRoute,
  EmployeesRoute: EmployeesRoute,
  GateEntryRoute: GateEntryRoute,
  GrnRoute: GrnRoute,
  InventoryRoute: InventoryRoute,
  LoginRoute: LoginRoute,
  MasterCoreRoute: MasterCoreRouteWithChildren,
  MasterDataRoute: MasterDataRoute,
  NotificationsRoute: NotificationsRoute,
  PurchaseOrderRoute: PurchaseOrderRoute,
  ReceivingRoute: ReceivingRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  VehicleQueueRoute: VehicleQueueRoute,
  VehicleVerificationRoute: VehicleVerificationRoute,
  WaveFlowRoute: WaveFlowRouteWithChildren,
  WorkCraftRoute: WorkCraftRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
