import { Link, Navigate } from "@tanstack/react-router";
import { ArrowRight, BarChart3, Boxes, ClipboardCheck, Database, Factory, LogOut, PackageCheck, Settings, Truck, Users, Warehouse, Waves, type LucideIcon } from "lucide-react";
import { useAuth, type ModuleKey } from "@/lib/auth";

type Item = { label: string; description: string; icon: LucideIcon };

const content: Record<Exclude<ModuleKey, "arrival">, { title: string; eyebrow: string; description: string; icon: LucideIcon; stats: Array<[string, string]>; items: Item[] }> = {
  master: { title: "Master Core", eyebrow: "Enterprise master data", description: "Govern the records used across every warehouse and operations workflow.", icon: Database, stats: [["Active suppliers", "248"], ["Customers", "1,284"], ["Item masters", "8,492"], ["Warehouses", "14"]], items: [{ label: "Suppliers", description: "Vendor records and compliance", icon: Users }, { label: "Customers", description: "Accounts and destinations", icon: Users }, { label: "Items", description: "SKUs, units and attributes", icon: Boxes }, { label: "Warehouses", description: "Plants, zones and storage", icon: Warehouse }, { label: "Employees", description: "Workforce master records", icon: Users }, { label: "Settings", description: "Governance and approvals", icon: Settings }] },
  wave: { title: "Wave Flow", eyebrow: "Outbound fulfillment", description: "Plan, release and control outbound work from order allocation through dispatch.", icon: Waves, stats: [["Open orders", "184"], ["Active waves", "12"], ["Pick progress", "78%"], ["Ready to ship", "42"]], items: [{ label: "Sales Orders", description: "Review outbound demand", icon: ClipboardCheck }, { label: "Allocation", description: "Reserve available inventory", icon: Boxes }, { label: "Wave Planning", description: "Group and schedule work", icon: Waves }, { label: "Picking", description: "Track pick execution", icon: PackageCheck }, { label: "Packing", description: "Cartons, labels and staging", icon: Boxes }, { label: "Dispatch", description: "Load and ship orders", icon: Truck }] },
  workcraft: { title: "Work Craft Flow", eyebrow: "Assembly management", description: "Control work orders, material consumption, quality checkpoints and completion.", icon: Factory, stats: [["Open work orders", "36"], ["In progress", "14"], ["Quality hold", "3"], ["Completed today", "22"]], items: [{ label: "Work Orders", description: "Create and schedule assembly", icon: ClipboardCheck }, { label: "Bill of Materials", description: "Components and consumption", icon: Boxes }, { label: "Assembly Stages", description: "Track production progress", icon: Factory }, { label: "Quality", description: "Inspections and checkpoints", icon: ClipboardCheck }, { label: "Finished Goods", description: "Serials and completion", icon: PackageCheck }, { label: "Reports", description: "Output and exceptions", icon: BarChart3 }] },
};

export function ModuleDashboard({ module }: { module: Exclude<ModuleKey, "arrival"> }) {
  const { user, canAccess, logout } = useAuth();
  if (!canAccess(module)) return <Navigate to="/dashboard" replace />;
  const page = content[module]; const Icon = page.icon;
  return <div className="min-h-screen bg-background">
    <header className="sticky top-0 z-20 border-b border-border bg-card/90 backdrop-blur"><div className="mx-auto flex h-16 max-w-[1400px] items-center gap-3 px-5"><Link to="/dashboard" className="grid size-10 place-items-center rounded-xl bg-primary text-primary-foreground"><Warehouse className="size-5" /></Link><div><p className="text-sm font-semibold">NexusWMS · {page.title}</p><p className="text-[11px] text-muted-foreground">{user?.role}</p></div><nav className="ml-8 hidden gap-1 md:flex"><Link to="/dashboard" className="rounded-lg px-3 py-2 text-sm text-muted-foreground hover:bg-accent">ArrivalFlow</Link><span className="rounded-lg bg-primary-soft px-3 py-2 text-sm font-medium text-primary">{page.title}</span></nav><button onClick={logout} className="ml-auto inline-flex items-center gap-2 rounded-xl border border-border px-3 py-2 text-sm text-muted-foreground hover:bg-destructive/10 hover:text-destructive"><LogOut className="size-4" /> Logout</button></div></header>
    <main className="mx-auto max-w-[1400px] px-5 py-8"><div className="rounded-3xl border border-border bg-card p-7 shadow-soft"><div className="flex items-start gap-4"><span className="grid size-12 place-items-center rounded-2xl bg-primary-soft text-primary"><Icon className="size-6" /></span><div><p className="text-xs font-semibold uppercase tracking-widest text-primary">{page.eyebrow}</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">{page.title} Dashboard</h1><p className="mt-2 max-w-2xl text-sm text-muted-foreground">{page.description}</p></div></div></div>
      <div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{page.stats.map(([label, value]) => <div key={label} className="rounded-2xl border border-border bg-card p-5"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-2 text-3xl font-semibold tabular-nums">{value}</p></div>)}</div>
      <div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{page.items.map((item) => <button key={item.label} className="group flex items-center gap-4 rounded-2xl border border-border bg-card p-5 text-left transition hover:-translate-y-0.5 hover:border-primary/40 hover:shadow-soft"><span className="grid size-11 place-items-center rounded-xl bg-muted text-primary"><item.icon className="size-5" /></span><span><span className="block font-semibold">{item.label}</span><span className="mt-1 block text-xs text-muted-foreground">{item.description}</span></span><ArrowRight className="ml-auto size-4 text-muted-foreground transition group-hover:translate-x-1 group-hover:text-primary" /></button>)}</div>
    </main>
  </div>;
}
