import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { Database, Lock, User } from "lucide-react";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { useAuth } from "@/lib/auth";
export const Route = createFileRoute("/login")({ component: Login });
function Login() { const auth = useAuth(); const navigate = useNavigate(); const [id, setId] = useState("admin@nexuswms.com"); const [password, setPassword] = useState("Admin@2026"); const [error, setError] = useState(""); return <div className="grid min-h-screen place-items-center bg-surface px-4"><form className="w-full max-w-sm rounded-2xl border border-border bg-background p-8 shadow-lg" onSubmit={(e) => { e.preventDefault(); const user = auth.login(id, password); if (!user) return setError("Invalid credentials or no Master Core access."); navigate({ to: "/" }); }}><div className="grid size-12 place-items-center rounded-xl bg-primary text-primary-foreground"><Database className="size-6" /></div><h1 className="mt-5 text-2xl font-semibold">Master Core sign in</h1><p className="mt-1 text-sm text-muted-foreground">Role-based access to enterprise master data.</p><div className="mt-6 space-y-4"><div><Label htmlFor="id">Employee ID or email</Label><div className="relative mt-2"><User className="absolute left-3 top-3 size-4 text-muted-foreground"/><Input id="id" className="pl-9" value={id} onChange={(e) => setId(e.target.value)} /></div></div><div><Label htmlFor="password">Password</Label><div className="relative mt-2"><Lock className="absolute left-3 top-3 size-4 text-muted-foreground"/><Input id="password" type="password" className="pl-9" value={password} onChange={(e) => setPassword(e.target.value)} /></div></div>{error && <p className="text-sm text-destructive">{error}</p>}<Button className="w-full">Sign in</Button></div><p className="mt-5 text-xs text-muted-foreground">Admin: admin@nexuswms.com / Admin@2026</p></form></div>; }
